### PR TITLE
Simplify finding the hip package

### PR DESCRIPTION
**Pull request by trixirt**
On Fedora, where hip is installed as an rpm, its cmake files can not be found and are reported as an error.

CMake Error at cmake/dependencies.cmake:44 (find_package):
  No "FindHIP.cmake" found in CMAKE_MODULE_PATH.

This change treats hip as a the normal package.

### CODE REVIEW

**Comment by malcolmroberts** [comment]
Thanks for this PR!  Looks like a good idea; we'll take a look and run it through the tests.

**Review by cgmb — APPROVED** [review]
In the currently released versions of HIP, hip-config.cmake only supports the AMD platform. You _must_ use the FindHIP.cmake module when building for the NVIDIA platform. However, this still does the module-mode search first and hip-config.cmake should eventually support the NVIDIA platform. So, I think this is fine.

I'm hoping to move away from FindHIP.cmake entirely. We'll probably want to clean up this whole section in the near future. It's a bit overly-complicated at the moment.

**Comment by malcolmroberts** [comment]
@cgmb  - we could also add some CI tests to check that this solves the use case described by @trixirt .  Might be a lot of docker images to cover.  Any thoughts?

**Comment by cgmb** [comment]
> @cgmb - we could also add some CI tests to check that this solves the use case described by @trixirt . Might be a lot of docker images to cover. Any thoughts?

I wouldn't worry about it. @trixirt and I can confirm this change is useful for Fedora and Debian, respectively. You can validate that it doesn't break the official ROCm builds, and that is probably sufficient.

Our whole method of using FindHIP.cmake is kind of silly. We're using FindHIP.cmake from the HIP package, so you need to find HIP to use FindHIP.cmake. Writing a bunch of tests might help prevent a few bugs, but I think it would be cheaper in the long run to eliminate the complexity that causes these sorts of bugs.

**Comment by heroxbd** [comment]
This commit is also useful to Gentoo.

By the [cmake documentation](Reference: https://cmake.org/cmake/help/latest/command/find_package.html),

>  Do not write find modules for packages that themselves build with
>  CMake. Instead provide a CMake package configuration file with the
>  package itself.

HIP uses cmake to build.  It should not have shipped a FindHIP.cmake (a cmake MODULE).

> You must use the FindHIP.cmake module when building for the NVIDIA platform.

For nVidia targets HIP is a wrapper around CUDA, it should hide the implementation detail of itself to hipFFT.

`FindCUDA.cmake` may be incorporated during the build of HIP.

**Review by evetsso — APPROVED** [review]

**Review by malcolmroberts — APPROVED** [review]

**Comment by cgmb** [comment]
Hi @heroxbd,

> HIP uses cmake to build. It should not have shipped a FindHIP.cmake (a cmake MODULE).

Just FYI, the folks that work on libraries like hipFFT are users of HIP, much like you. They work for AMD, but not on HIP itself. While they certainly can relay concerns to the HIP team, it's usually better for affected users to file issues directly on the repo for the component that the problem originates from. It helps prevent duplicate reports, it's less work for the library teams, and it helps keep you in the loop on any updates.

**Comment by heroxbd** [comment]
> eam, it's usually be

Thanks @cgmb!  Sure, we are sorting out the patches carried by Gentoo `hip` package and report them to the HIP team.

**Comment by cgmb** [comment]
Thank you for doing that. I know it's a fair bit of effort to upstream things, but it is very much appreciated.

**Pull request merged**
